/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI and Humanoid Robotics",
  "tagline": "From Embodiment to Real-World Intelligence",
  "url": "https://zohaibfaiz0.github.io",
  "baseUrl": "/physical-ai-book/",
  "onBrokenLinks": "warn",
  "favicon": "img/logo.svg",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\AA\\Desktop\\sp+\\book\\sidebars.js",
          "editUrl": "https://github.com/zohaibfaiz0/physical-ai-book"
        },
        "blog": false,
        "theme": {
          "customCss": "C:\\Users\\AA\\Desktop\\sp+\\book\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "Physical AI & Humanoid Robotics",
      "logo": {
        "alt": "Physical AI and Humanoid Robotics Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "https://github.com/zohaibfaiz0/physical-ai-book",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<div class=\"navbar__item--rag-status\"><span class=\"rag-status-indicator\"></span>RAG Active</div>"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<div id=\"navbar-chat-container\"></div>"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/intro"
            },
            {
              "label": "Week 1-2: Foundations",
              "to": "/docs/chapters/01-weeks-1-2-foundations/"
            },
            {
              "label": "Week 3-5: ROS2",
              "to": "/docs/chapters/02-weeks-3-5-ros2/"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "GitHub Repository",
              "href": "https://github.com/zohaibfaiz0/physical-ai-book"
            },
            {
              "label": "Docusaurus",
              "href": "https://docusaurus.io"
            }
          ]
        },
        {
          "title": "Built with AI",
          "items": [
            {
              "label": "Gemini 2.5 Flash",
              "href": "https://deepmind.google/technologies/gemini/"
            },
            {
              "label": "Qdrant Vector DB",
              "href": "https://qdrant.tech"
            },
            {
              "label": "Neon Postgres",
              "href": "https://neon.tech"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Physical AI and Humanoid Robotics Book. Built with Docusaurus. <div class=\"footer__rag-stats\">RAG Queries Served: <span id=\"rag-queries-count\">∞</span> | Live Status: <span class=\"rag-status-indicator\"></span> Active</div>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "scripts": [
    {
      "src": "/js/navbar-chat.js",
      "async": true
    }
  ],
  "plugins": [
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 80,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ]
  ],
  "themes": [
    [
      "C:\\Users\\AA\\Desktop\\sp+\\book\\node_modules\\@easyops-cn\\docusaurus-search-local\\dist\\server\\server\\index.js",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "docsDir": "docs",
        "docsRouteBasePath": "/",
        "blogDir": "blog",
        "blogRouteBasePath": "/blog/",
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true,
        "searchBarPosition": "navbar",
        "searchBarShortcut": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
